# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-18 04:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lifeline', '0002_auto_20170318_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_category',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='lifeline.Item_Category'),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_description',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_location',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_priority',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='lifeline.Item_Priority'),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_type',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='lifeline.Item_Type'),
        ),
    ]
