# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-18 04:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lifeline', '0004_auto_20170318_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lifeline.User'),
        ),
    ]
