# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-18 06:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lifeline', '0005_auto_20170318_1503'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='item_location',
            new_name='item_latitude',
        ),
        migrations.AddField(
            model_name='item',
            name='item_longitude',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
