# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-18 11:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lifeline', '0007_auto_20170318_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
